// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PaidByDropdownController from "./paid_by_dropdown_controller"
application.register("paid-by-dropdown", PaidByDropdownController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import SplitByDropdownController from "./split_by_dropdown_controller"
application.register("split-by-dropdown", SplitByDropdownController)
