// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ExpenseParticipantsController from "./expense_participants_controller"
application.register("expense-participants", ExpenseParticipantsController)

import ExpenseSharesController from "./expense_shares_controller"
application.register("expense-shares", ExpenseSharesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ItemFormController from "./item_form_controller"
application.register("item-form", ItemFormController)

import Itemized__GrandTotalController from "./itemized/grand_total_controller"
application.register("itemized--grand-total", Itemized__GrandTotalController)

import Itemized__ItemController from "./itemized/item_controller"
application.register("itemized--item", Itemized__ItemController)

import Itemized__SubtotalController from "./itemized/subtotal_controller"
application.register("itemized--subtotal", Itemized__SubtotalController)

import PaidByDropdownController from "./paid_by_dropdown_controller"
application.register("paid-by-dropdown", PaidByDropdownController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import SplitByAccordionController from "./split_by_accordion_controller"
application.register("split-by-accordion", SplitByAccordionController)

import SplitByDropdownController from "./split_by_dropdown_controller"
application.register("split-by-dropdown", SplitByDropdownController)
