// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import ItemForm from "./item_form_controller"
application.register("item-form", ItemForm)

import ExpenseParticipantsController from "./expense_participants_controller"
application.register("expense-participants", ExpenseParticipantsController)

import ExpenseSharesController from "./expense_shares_controller"
application.register("expense-shares", ExpenseSharesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PaidByDropdownController from "./paid_by_dropdown_controller"
application.register("paid-by-dropdown", PaidByDropdownController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import SplitByAccordionController from "./split_by_accordion_controller"
application.register("split-by-accordion", SplitByAccordionController)

import SplitByDropdownController from "./split_by_dropdown_controller"
application.register("split-by-dropdown", SplitByDropdownController)
